import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';

// Dev-only middleware: handles /api/send-email locally using Resend REST API
// In production (Vercel), api/send-email.js takes over automatically
function buildEmailHtml(quote, fwd, fromName, fromEmail) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
  body{font-family:'Segoe UI',Arial,sans-serif;background:#FFF8F0;margin:0;padding:20px;color:#4B3A2A}
  .wrap{max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #FFE5CC}
  .hdr{background:#F97316;padding:22px 30px;text-align:center}
  .hdr h1{color:#fff;margin:0;font-size:22px;font-weight:700}
  .body{padding:30px}
  .greeting{font-size:15px;font-weight:600;color:#1C1009;margin-bottom:10px}
  table{width:100%;border-collapse:collapse;margin-bottom:22px}
  td{padding:8px 10px;font-size:13px;border-bottom:1px solid #FFF8F0}
  td.lbl{font-weight:600;background:#FFFBF5;width:38%}
  .cta{background:#FFFBF5;border:1px dashed #F97316;border-radius:8px;padding:18px;margin-bottom:22px}
  .cta h3{margin:0 0 8px;color:#F97316;font-size:14px}
  .cta ol{margin:0;padding-left:18px;font-size:13px;line-height:1.7}
  .deadline{margin-top:12px;background:#FFE5CC;display:inline-block;padding:6px 12px;border-radius:6px;font-size:13px;font-weight:700}
  .ftr{background:#FFFBF5;border-top:1px solid #FFE5CC;padding:16px 30px;text-align:center;font-size:11px;color:#8C7560}
</style></head><body>
<div class="wrap">
  <div class="hdr"><h1>FREIGHTBID LOGISTICS</h1></div>
  <div class="body">
    <div class="greeting">Dear ${fwd.name} (${fwd.company}),</div>
    <p style="font-size:13px;margin-bottom:22px">We have a new shipment quotation request and would like to invite you to submit your most competitive freight bid.</p>
    <table>
      <tr><td class="lbl">Reference ID</td><td><strong>${quote.referenceId}</strong></td></tr>
      <tr><td class="lbl">Origin</td><td>${quote.origin}</td></tr>
      <tr><td class="lbl">Destination</td><td>${quote.destination}</td></tr>
      <tr><td class="lbl">Cargo Type</td><td>${quote.cargoType}</td></tr>
      <tr><td class="lbl">Weight</td><td>${quote.weight} kg</td></tr>
      <tr><td class="lbl">Dimensions</td><td>${quote.dimensions || 'N/A'}</td></tr>
      <tr><td class="lbl">Declared Value</td><td>${quote.declaredValue ? `$${Number(quote.declaredValue).toLocaleString()}` : 'N/A'}</td></tr>
      <tr><td class="lbl">Incoterms</td><td>${quote.incoterms}</td></tr>
      <tr><td class="lbl">Mode</td><td>${quote.mode}</td></tr>
      <tr><td class="lbl">Ready Date</td><td>${quote.readyDate || 'ASAP'}</td></tr>
      ${quote.specialInstructions ? `<tr><td class="lbl">Special Instructions</td><td>${quote.specialInstructions}</td></tr>` : ''}
    </table>
    <div class="cta">
      <h3>Please reply with your bid:</h3>
      <ol>
        <li><strong>Quoted Price</strong> – Total all-inclusive rate (USD or INR)</li>
        <li><strong>Transit Time</strong> – Estimated ETD / ETA</li>
        <li><strong>Remarks</strong> – Any surcharges or conditions</li>
      </ol>
      <div class="deadline">Deadline: ${quote.deadline ? new Date(quote.deadline).toLocaleDateString() : 'ASAP'}</div>
    </div>
  </div>
  <div class="ftr">Generated by <strong>FreightBid</strong> — ${fromEmail}</div>
</div></body></html>`;
}

function devEmailPlugin(env) {
  return {
    name: 'freightbid-email-api',
    configureServer(server) {
      server.middlewares.use('/api/send-email', (req, res) => {
        if (req.method !== 'POST') {
          res.statusCode = 405;
          res.end(JSON.stringify({ error: 'Method not allowed' }));
          return;
        }

        let body = '';
        req.on('data', chunk => (body += chunk.toString()));
        req.on('end', async () => {
          res.setHeader('Content-Type', 'application/json');
          try {
            const { quote, forwarders } = JSON.parse(body);
            const apiKey    = env.RESEND_API_KEY    || '';
            const fromName  = env.RESEND_FROM_NAME  || 'FreightBid Logistics';
            const fromEmail = env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';
            const isMock    = !apiKey || apiKey.startsWith('re_your');

            if (isMock) {
              console.log(`\n[FreightBid] MOCK MODE — ${forwarders.length} forwarder(s) for ${quote.referenceId}`);
              forwarders.forEach(f => console.log(`  → ${f.name} <${f.email}>`));
              return res.end(JSON.stringify({ isMock: true, sentCount: forwarders.length, message: `Mock mode active. Add RESEND_API_KEY to frontend/.env to send real emails.` }));
            }

            // Real Resend send
            const results = [];
            for (const fwd of forwarders) {
              const r = await fetch('https://api.resend.com/emails', {
                method: 'POST',
                headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  from:    `${fromName} <${fromEmail}>`,
                  to:      [fwd.email],
                  subject: `Freight Quotation Request – ${quote.referenceId} | ${quote.origin} to ${quote.destination}`,
                  html:    buildEmailHtml(quote, fwd, fromName, fromEmail)
                })
              });
              const data = await r.json();
              results.push(r.ok
                ? { email: fwd.email, status: 'success', id: data.id }
                : { email: fwd.email, status: 'failed',  error: data.message }
              );
            }

            const sentCount = results.filter(r => r.status === 'success').length;
            res.end(JSON.stringify({ isMock: false, sentCount, totalCount: forwarders.length, results, message: `Sent to ${sentCount}/${forwarders.length} forwarders.` }));
          } catch (err) {
            res.statusCode = 500;
            res.end(JSON.stringify({ error: err.message }));
          }
        });
      });
    }
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), ''); // load .env without VITE_ prefix restriction
  return {
    plugins: [react(), devEmailPlugin(env)],
    server: { port: 5173 }
  };
});
