// Vercel Serverless Function — Production email sender via Resend REST API
// Lives at: frontend/api/send-email.js
// Vercel auto-discovers this as POST /api/send-email

function buildEmailHtml(quote, forwarder, fromName, fromEmail) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Freight Quotation Request</title>
<style>
  body{font-family:'Segoe UI',Arial,sans-serif;background:#FFF8F0;margin:0;padding:20px;color:#4B3A2A}
  .wrap{max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;border:1px solid #FFE5CC;box-shadow:0 4px 12px rgba(249,115,22,.08)}
  .hdr{background:#F97316;padding:22px 30px;text-align:center}
  .hdr h1{color:#fff;margin:0;font-size:22px;font-weight:700;letter-spacing:.5px}
  .body{padding:30px}
  .greeting{font-size:15px;font-weight:600;color:#1C1009;margin-bottom:10px}
  .intro{font-size:13px;line-height:1.6;margin-bottom:22px}
  .sec{font-size:11px;font-weight:700;color:#F97316;text-transform:uppercase;letter-spacing:1px;border-bottom:1px solid #FFE5CC;padding-bottom:4px;margin-bottom:12px}
  table{width:100%;border-collapse:collapse;margin-bottom:22px}
  td{padding:8px 10px;font-size:13px;border-bottom:1px solid #FFF8F0}
  td.lbl{font-weight:600;color:#1C1009;width:38%;background:#FFFBF5}
  .cta{background:#FFFBF5;border:1px dashed #F97316;border-radius:8px;padding:18px;margin-bottom:22px}
  .cta h3{margin:0 0 8px;color:#F97316;font-size:14px}
  .cta ol{margin:0;padding-left:18px;font-size:13px;line-height:1.7}
  .deadline{margin-top:12px;background:#FFE5CC;display:inline-block;padding:6px 12px;border-radius:6px;font-size:13px;font-weight:700;color:#1C1009}
  .ftr{background:#FFFBF5;border-top:1px solid #FFE5CC;padding:16px 30px;text-align:center;font-size:11px;color:#8C7560}
</style></head><body>
<div class="wrap">
  <div class="hdr"><h1>FREIGHTBID LOGISTICS</h1></div>
  <div class="body">
    <div class="greeting">Dear ${forwarder.name} (${forwarder.company}),</div>
    <div class="intro">We have a new shipment quotation request and would like to invite you to submit your most competitive freight bid.</div>
    <div class="sec">Shipment Details</div>
    <table>
      <tr><td class="lbl">Reference ID</td><td><strong>${quote.referenceId}</strong></td></tr>
      <tr><td class="lbl">Origin</td><td>${quote.origin}</td></tr>
      <tr><td class="lbl">Destination</td><td>${quote.destination}</td></tr>
      <tr><td class="lbl">Cargo Type</td><td>${quote.cargoType}</td></tr>
      <tr><td class="lbl">Weight</td><td>${quote.weight} kg</td></tr>
      <tr><td class="lbl">Dimensions (L×W×H)</td><td>${quote.dimensions || 'N/A'}</td></tr>
      <tr><td class="lbl">Declared Value</td><td>${quote.declaredValue ? `$${Number(quote.declaredValue).toLocaleString()}` : 'N/A'}</td></tr>
      <tr><td class="lbl">Incoterms</td><td>${quote.incoterms}</td></tr>
      <tr><td class="lbl">Mode of Shipment</td><td>${quote.mode}</td></tr>
      <tr><td class="lbl">Cargo Ready Date</td><td>${quote.readyDate || 'ASAP'}</td></tr>
      ${quote.specialInstructions ? `<tr><td class="lbl">Special Instructions</td><td>${quote.specialInstructions}</td></tr>` : ''}
    </table>
    <div class="cta">
      <h3>Please reply with your bid:</h3>
      <ol>
        <li><strong>Quoted Price</strong> – Total all-inclusive rate (USD or INR)</li>
        <li><strong>Transit Time</strong> – Estimated ETD / ETA</li>
        <li><strong>Remarks</strong> – Surcharges, exclusions, or conditions</li>
      </ol>
      <div class="deadline">Response Deadline: ${quote.deadline ? new Date(quote.deadline).toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'}) : 'ASAP'}</div>
    </div>
  </div>
  <div class="ftr">Generated by <strong>FreightBid Logistics Platform</strong> &mdash; ${fromEmail}</div>
</div>
</body></html>`;
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { quote, forwarders } = req.body;

  if (!quote || !forwarders || forwarders.length === 0) {
    return res.status(400).json({ error: 'quote and forwarders are required.' });
  }

  const apiKey    = process.env.RESEND_API_KEY    || '';
  const fromName  = process.env.RESEND_FROM_NAME  || 'FreightBid Logistics';
  const fromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';
  const isMock    = !apiKey || apiKey.startsWith('re_your');

  if (isMock) {
    console.log(`[FreightBid] MOCK MODE — would email ${forwarders.length} forwarder(s) for ${quote.referenceId}`);
    forwarders.forEach(f => console.log(`  → ${f.name} <${f.email}>`));
    return res.json({ isMock: true, sentCount: forwarders.length, message: `Mock: add RESEND_API_KEY to .env to send real emails.` });
  }

  const results = [];
  for (const fwd of forwarders) {
    try {
      const r = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          from: `${fromName} <${fromEmail}>`,
          to:   [fwd.email],
          subject: `Freight Quotation Request – ${quote.referenceId} | ${quote.origin} to ${quote.destination}`,
          html: buildEmailHtml(quote, fwd, fromName, fromEmail)
        })
      });
      const data = await r.json();
      results.push(r.ok ? { email: fwd.email, status: 'success', id: data.id } : { email: fwd.email, status: 'failed', error: data.message });
    } catch (err) {
      results.push({ email: fwd.email, status: 'failed', error: err.message });
    }
  }

  const sentCount = results.filter(r => r.status === 'success').length;
  return res.json({ isMock: false, sentCount, totalCount: forwarders.length, results, message: `Sent to ${sentCount}/${forwarders.length} forwarders.` });
}
